# Generated by Django 6.0.4 on 2026-05-02 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='caste',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
