# Generated by Django 6.0.4 on 2026-05-03 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_customuser_lastseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_match_recommendations_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_match_recommendations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'candidate_id'],
                'constraints': [models.UniqueConstraint(fields=('viewer', 'candidate'), name='unique_ai_match_viewer_candidate')],
            },
        ),
    ]
