from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    RegisterView,
    MatchFeedView,
    UserSearchView,
    PreferencesView,
    ProfileView,
    UserDetailView,
    AppConfigurationView,
    EngagementSummaryView,
    ChatContactsView,
    ChatMessagesView,
    CreateFamilyGroupChatView,
    GroupChatListView,
    GroupChatMessagesView,
    CaptchaLoginView,
    GoogleLoginView,
    RegisterInit2FAView,
    RegisterVerify2FAView,
    ToggleFavoriteView,
    AvailableInterestsView,
    AvailableFiltersView,
    FamilyConnectionView,
    ReportUserView,
    BlockUserView,
    BlockedUsersListView,
    PasswordResetRequestView,
    PasswordResetVerifyView,
    FamilyMemberView,
)
from .profile_search_views import SearchProfilesView

urlpatterns = [
    path('register/', RegisterView.as_view(), name='auth_register'),
    path('register/init-2fa/', RegisterInit2FAView.as_view(), name='register_init_2fa'),
    path('register/verify-2fa/', RegisterVerify2FAView.as_view(), name='register_verify_2fa'),
    path('login/', CaptchaLoginView.as_view(), name='captcha_login'),
    path('google-login/', GoogleLoginView.as_view(), name='google_login'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('feed/', MatchFeedView.as_view(), name='match_feed'),
    path('search/users/', UserSearchView.as_view(), name='user_search'),
    path('preferences/', PreferencesView.as_view(), name='preferences'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('user/<int:user_id>/', UserDetailView.as_view(), name='user_detail'),
    path('favorites/toggle/', ToggleFavoriteView.as_view(), name='toggle_favorite'),
    path('app-configuration/', AppConfigurationView.as_view(), name='app_configuration'),
    path('engagement-summary/', EngagementSummaryView.as_view(), name='engagement_summary'),
    path('chat/contacts/', ChatContactsView.as_view(), name='chat_contacts'),
    path('chat/messages/<int:contact_id>/', ChatMessagesView.as_view(), name='chat_messages'),
    path('chat/groups/family/', CreateFamilyGroupChatView.as_view(), name='create_family_group_chat'),
    path('chat/groups/<int:group_id>/messages/', GroupChatMessagesView.as_view(), name='group_chat_messages'),
    path('chat/groups/', GroupChatListView.as_view(), name='group_chat_list'),
    path('interests/available/', AvailableInterestsView.as_view(), name='available_interests'),
    path('filters/', AvailableFiltersView.as_view(), name='available_filters'),
    path('search/', SearchProfilesView.as_view(), name='profile_search'),
    path('family/', FamilyConnectionView.as_view(), name='family_connections'),
    path('report/', ReportUserView.as_view(), name='report_user'),
    path('block/', BlockUserView.as_view(), name='block_user'),
    path('blocked-users/', BlockedUsersListView.as_view(), name='blocked_users'),
    path('password-reset/request/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('password-reset/verify/', PasswordResetVerifyView.as_view(), name='password_reset_verify'),
    path('family-members/', FamilyMemberView.as_view(), name='family_members'),
]
